name: area_connect
description: Local People connect to each other.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  app_version_update: ^6.2.0
  audioplayers: ^6.6.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.4.0
  dio: ^5.9.2
  equatable: ^2.0.7
  file_picker: ^11.0.2
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^21.0.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  fpdart: ^1.2.0
  geolocator: ^14.0.2
  go_router: ^17.1.0
  iconsax_plus: ^1.0.0
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^3.0.0
  intl: ^0.20.2
  local_auth: ^3.0.1
  logger: ^2.6.2
  package_info_plus: ^9.0.1
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  record: ^7.0.0
  share_plus: ^12.0.2
  shared_preferences: ^2.5.4
  skeletonizer: ^2.1.3
  smooth_page_indicator: ^2.0.1
  socket_io_client: ^3.1.4
  url_launcher: ^6.3.1
  video_player: ^2.11.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides: null

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env
